### ISSUE TITLE
can you share the video you made if possible?

### ISSUE THREAD

**Issue by swagath** [pageauc/rpi-timelapse#1]

**Comment by pageauc** [comment]
This project has not been maintained for 3 years and I now use pi-timolo https://github.com/pageauc/pi-timolo

I have several videos that were done the first year I used this code and then moved on to develop pi-timolo.  

This video was probably the only long timelapse I did using this early version even though the description it has pi-timolo in title.  winter timelapse https://youtu.be/pFkt0ZOrPzg
short version https://youtu.be/x06MUtLAhcU
palms and Ice https://youtu.be/XjrhgLTILdo

Other projects were done during the short testing period before I went south for the winter when the above winter timelapse was taken.  I did not post them on YouTube.  I developed this code in a rush before going south and that winter created the PI-TIMOLO project and just left rpi-timelapse code on GitHub bud did not maintain it after PI-TIMOLO was developed.  This code was when I was still learning python programming language so it is a snapshot of a beginner learning to code.

The history is that I had been working on timelapse and motion and decided to combine the two sets of code into PI-TIMOLO.  Since then PI-TIMOLO has evolved a lot and I have not done anything with this rpi-timelapse code.  If there is interest I can review code and update it as a stand alone timelapse only program.  You can also try my PI-TIMOLO project but it is a lot more complex and does a lot more things and can be configured different ways with plugins, RClone remote storage, WebServer, Admin Menu system, Etc 

Thanks for your interest and let me know if you have any questions.

**Comment by swagath** [comment]
started using PI-TIMOLO, great work and thanks!
